/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentgrades;


/**
 * File Name: Student_Grades
 * Name: Ellen Wang
 * Date: May 3, 2020
 * Description: Create a student grades application that includes two dimensional array. the program stimulates a grade book for a class of 15 students who each have four test scores
 */
public class Student_Grades extends javax.swing.JFrame {

    String[][] NamesA = new String [24][6];
    //defines a two-dimensional array
    
    int index = 0;
    //value for one array indec
    
    /**
     * Creates new form Student_Grades
     */
    public Student_Grades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        test1Label = new javax.swing.JLabel();
        test2Label = new javax.swing.JLabel();
        test3Label = new javax.swing.JLabel();
        test4Label = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        saverageButton = new javax.swing.JButton();
        caverageButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputText = new javax.swing.JTextArea();
        firstnameInput = new javax.swing.JTextField();
        lastnameInput = new javax.swing.JTextField();
        test1Input = new javax.swing.JTextField();
        test2Input = new javax.swing.JTextField();
        test3Input = new javax.swing.JTextField();
        test4Input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        titleLabel.setText("Student Grades ");

        fnameLabel.setText("First Name:");

        lnameLabel.setText("Last Name:");

        test1Label.setText("Test 1:");

        test2Label.setText("Test 2:");

        test3Label.setText("Test 3:");

        test4Label.setText("Test 4:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        listButton.setText("List");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        saverageButton.setText("Student Average");
        saverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saverageButtonActionPerformed(evt);
            }
        });

        caverageButton.setText("Course Average");
        caverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caverageButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        OutputText.setColumns(20);
        OutputText.setRows(5);
        jScrollPane1.setViewportView(OutputText);

        test2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test2InputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lnameLabel)
                                .addGap(45, 45, 45)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saverageButton)
                    .addComponent(caverageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fnameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(test1Label)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(test1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(test2Label)
                                        .addComponent(test3Label)
                                        .addComponent(test4Label))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(test3Input)
                                        .addComponent(test2Input)
                                        .addComponent(test4Input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(listButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(exitButton)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel)
                    .addComponent(lnameLabel)
                    .addComponent(lastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test1Label)
                            .addComponent(test1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test2Label)
                            .addComponent(test2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(saverageButton))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test3Label)
                            .addComponent(test3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(test4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(test4Label)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listButton)
                            .addComponent(caverageButton))
                        .addGap(9, 9, 9)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void test2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_test2InputActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        try{
        String temp = "";
        //defines the variable and makes it equal nothing 
        
        for (int index3 = 0; index3 <= index-1; index3++){
            for (int index2 = 0; index2 <= 5; index2++){
                
                temp = temp + NamesA [index3][index2];
            }
            temp += "\n";
        }
        //creates a limit for index3 and index2 and has the variable temp assigned a value
        
       
        
        OutputText.setText("First\t" + "Last\t" + "Test1\t" + "Test2\t" + "Test3\t" + "Test4\t" + "\n" + temp);
        //sets the text
        } catch (Exception e){
        OutputText.setText("ATTENTION There Is A Error In Your Input"); }
        //displays an error message if the program wont run     
    }//GEN-LAST:event_listButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
        //closes the project when the button is clicked
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try{
        String firstName, lastName, test1, test2, test3, test4;
        //defines strings
        
        firstName = firstnameInput.getText(); 
        lastName = lastnameInput.getText();
        test1 = test1Input.getText();
        test2 = test2Input.getText();
        test3 = test3Input.getText();
        test4 = test4Input.getText();
        //stores the user input values into a string variable
        
        NamesA [index] [0] = firstName + "\t";
        NamesA [index] [1] = lastName+ "\t";
        NamesA [index] [2] = test1 + "\t";
        NamesA [index] [3] = test2+ "\t";
        NamesA [index] [4] = test3 + "\t";
        NamesA [index] [5] = test4 + "\t";
        //assigns the array a value
        
        index++;
        //increases the index by one each time the add button is pressed
        } catch (Exception e){
        OutputText.setText("ATTENTION There Is A Error In Your Input"); }
        //displays an error message if the program wont run 
    }//GEN-LAST:event_addButtonActionPerformed

    private void saverageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saverageButtonActionPerformed
        try {
        String temp = ""; 
        //defines temp as a string variable
        
        
        
        for (int index3 = 0; index3 <= index-1; index3++){
            for(int index2 = 0; index2 <= 5; index2++){
                temp = temp + NamesA[index3][index2];}
                    temp += "\n";}
        //creates a limit for index3 and index2 and has the variable temp assigned a value
        
        OutputText.setText("First\t" + "Last\t" + " Test1\t" + " Test2\t" + " Test3\t" + " Test4\t" + "\n" + temp);
        //sets the text
        
        String firstName, lastName;
        //defines the variables as strings
        
        firstName = firstnameInput.getText();
        lastName = lastnameInput.getText();
        //gets the user input value and stores it in the variables
        
        int studentavgs = 0;
        //defines a variable as an int and sets it equal to zero
        
        int test1, test2, test3, test4;
        //defines the variables as integers
        
        test1 = Integer.parseInt(test1Input.getText());
        test2 = Integer.parseInt(test2Input.getText());
        test3 = Integer.parseInt(test3Input.getText());
        test4 = Integer.parseInt(test4Input.getText());
        //stores user input value into a int variable 
        
        studentavgs = (test1 + test2 + test3 + test4)/4 ;
        //calculates the student avg
        
        OutputText.setText("First\t" + "Last\t" + " Test1\t" + " Text2\t" + " Text3\t" + " Text4\t" + "\n" + temp + "\n" + "The average of " + firstName + " " + lastName + " is: " + studentavgs);
        //prints out the output message 
        } catch (Exception e){
        OutputText.setText("ATTENTION There Is A Error In Your Input"); }
        //displays an error message if the program wont run 
    }//GEN-LAST:event_saverageButtonActionPerformed

    private void caverageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caverageButtonActionPerformed
        try {
        String temp = " ";
        //defines temp 
            
        for(int index3 = 0; index3 <=index-1; index3++){
            for (int index2 = 0; index2 <= 5; index2++){ 
                  temp= temp + NamesA[index3][index2];}
                    temp += "\n";}        
        //creates a limit for index3 and index2 and has the variable temp assigned a value

        OutputText.setText("First\t" + "Last\t" + " Test1\t"+ " Test2\t"+ " Test3\t"+ " Test4\t" + "\n" + temp); 
        //sets the output text
       
        int courseavg1 = 0, courseavg2 = 0, courseavg3 = 0, courseavg4 = 0; 
        //defines a variable for the course and sets it equal to 0
        
        for (int row=0; row <= index-1; row++){
            courseavg1 = courseavg1 + Integer.parseInt(NamesA[row][2].trim());
            courseavg2 = courseavg2 + Integer.parseInt(NamesA[row][3].trim());
            courseavg3 = courseavg3 + Integer.parseInt(NamesA[row][4].trim()); 
            courseavg4 = courseavg4 + Integer.parseInt(NamesA[row][5].trim());}
        //gets the user input value and adds it to the course avg
    
        int course1, course2, course3,course4;
        //defines the variables as integers
        
        course1 = courseavg1/index; 
        course2 = courseavg2/index; 
        course3 = courseavg3/index; 
        course4 = courseavg4/index; 
        //calculates the course avg
        
        OutputText.setText("First \t"+"Last \t"+" Test1 \t"+" Test2 \t"+" Test3 \t"+" Test4 \t"+ "\n" + temp + "\n"+ "The average: Test1 \tTest2 \tTest3 \tTest4"+"\n" +" \t"+ course1 +"\t" + course2+ " \t" + course3+ " \t" + course4  ); 
        //sets output text 
        } catch (Exception e){
        OutputText.setText("ATTENTION There Is A Error In Your Input"); }
        //displays an error message if the program wont run 
    }//GEN-LAST:event_caverageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Grades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputText;
    private javax.swing.JButton addButton;
    private javax.swing.JButton caverageButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField firstnameInput;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameInput;
    private javax.swing.JButton listButton;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JButton saverageButton;
    private javax.swing.JTextField test1Input;
    private javax.swing.JLabel test1Label;
    private javax.swing.JTextField test2Input;
    private javax.swing.JLabel test2Label;
    private javax.swing.JTextField test3Input;
    private javax.swing.JLabel test3Label;
    private javax.swing.JTextField test4Input;
    private javax.swing.JLabel test4Label;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
